Version: 1
Script ("Default PhysX Viewer Script","Viewer")
{
	Plugin ("PhysXViewerPlugin","PhysX Viewer","1.0","Viewer")
	{
		Parameter ("NiPluginToolkit Renderer","2");
		Parameter ("DebugOutput","TRUE");
		Parameter ("GroundPlane","FALSE");
		Parameter ("GroundHeight","0.000000");
		Parameter ("FullScreen","FALSE");
		Parameter ("ResolutionWidth","800");
		Parameter ("ResolutionHeight","600");
	}
}
