//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MiResource.rc
//
#define IDS_NETIMMERSE                  1
#define IDS_NI_UTIL_CLASS_NAME          1
#define IDS_LIBDESC                     2
#define IDS_LONG_DESC                   3
#define IDS_NI_UTIL_LONG_DESC           3
#define IDS_SHORT_DESC                  4
#define IDS_NI_UTIL_SHORT_DESC          4
#define IDS_ROB_PHILLIPS                5
#define IDS_COPYRIGHT_NDL               6
#define IDS_NI_ROLLUP_LABEL             7
#define IDS_NI_MAIN_LABEL               7
#define IDS_NI_EXPORT_LONG_DESC         8
#define IDS_NI_EXPORT_SHORT_DESC        9
#define IDS_NI_EXPORT_CLASS_NAME        10
#define IDS_NI_LIB_DESC                 11
#define IDS_NI_BASE                     12
#define IDS_NI_DARK                     13
#define IDS_NI_ERROR_NOT_IN_PATH        14
#define IDS_NI_DETAIL                   15
#define IDS_NI_IMPORT_CLASS_NAME        16
#define IDS_NI_IMPORT_LONG_DESC         17
#define IDS_NI_IMPORT_SHORT_DESC        18
#define IDS_NI_ERROR_OPENING_FILE       19
#define IDS_NI_ERROR_READ               20
#define IDS_NI_IMPORT_ERR_TITLE         21
#define IDS_NI_ERROR_INVALID_FILE       22
#define IDS_NI_EXPORT_ERR_TITLE         23
#define IDS_NI_ERROR_CANT_CREATE        24
#define IDS_NI_ERROR_WRITE              25
#define IDS_NI_ERROR_FCLOSE             26
#define IDS_NI_UTIL_ERR_TITLE           27
#define IDS_NI_ERROR_MEM_FAIL           28
#define IDS_NI_ERROR_GENERIC            29
#define IDS_NI_ERROR_NO_RENDERER        30
#define IDS_NI_REGISTER_LABEL           31
#define IDS_NI_HEADFIRST_LABEL          31
#define IDS_NI_QUICKSAVE_LABEL          31
#define IDS_NI_RENDERER_LABEL           32
#define IDS_NI_INTERACTION_LABEL        33
#define IDS_NI_KEYBOARD_LABEL           34
#define IDS_STRING35                    35
#define IDS_NI_MOUSE_LABEL              36
#define IDS_NI_ERROR_MISSING_DEMO       37
#define IDS_TEMP                        38
#define IDS_NI_IK_LABEL                 39
#define IDS_NI_NONE                     40
#define IDS_CLASSNAME                   41
#define IDS_PARAMETERS                  42
#define IDS_NETIMMERSE_DESC             43
#define IDS_DIFF_COLOR                  44
#define IDS_PARAMCHG                    45
#define IDS_NI_BASE_I                   46
#define IDS_NI_DARK_I                   47
#define IDS_NI_DETAIL_I                 48
#define IDS_NI_DECAL                    49
#define IDS_NI_BUMP                     50
#define IDS_NI_GLOSS                    51
#define IDS_NI_GLOW                     52
#define IDS_NI_DECAL_I                  53
#define IDS_NI_BUMP_I                   54
#define IDS_NI_GLOSS_I                  55
#define IDS_NI_GLOW_I                   56
#define IDS_NI_AMBIENT                  57
#define IDS_NI_SPECULAR                 58
#define IDS_NI_EMITTANCE                59
#define IDS_NI_SHININESS                60
#define IDS_NI_ALPHA                    61
#define IDS_AMB_COLOR                   62
#define IDS_SPEC_COLOR                  63
#define IDS_EMITTANCE                   64
#define IDS_NI_SHADER                   65
#define IDS_NI_TEST_REF                 66
#define IDS_NI_TEST_MODE                67
#define IDS_NI_ALPHATESTENABLE          68
#define IDS_NI_SRC_BLEND                69
#define IDS_NI_DEST_BLEND               70
#define IDS_NI_APPLY_MODE               71
#define IDS_NI_SRC_VERTEX_MODE          72
#define IDS_NI_LIGHTING_MODE            73
#define IDS_NI_VERTEXCOLORENABLE        74
#define IDS_NI_SPECULARENABLE           75
#define IDS_NI_NOSORTER                 76
#define IDS_NI_DIFFUSE                  78
#define IDS_NI_PCOLOR                   79
#define IDS_NI_POPAC                    80
#define IDS_NI_NORMAL                   81
#define IDS_NI_PARALLAX                 82
#define IDS_NI_PARALLAX_OFFSET          83
#define IDD_PACKETIN                    101
#define IDD_NI_PANEL                    101
#define IDD_RENDERER_PANEL              101
#define IDD_MAIN_PANEL                  106
#define IDS_NI_ALPHA_MODE               106
#define IDD_REGISTER_PANEL              107
#define IDD_HEADFIRST_PANEL             107
#define IDD_QUICKSAVE_PANEL             107
#define IDD_INTERACTION_PANEL           108
#define IDD_KEYBOARD_PANEL              109
#define IDS_NI_BUMP_MAGNITUDE           109
#define IDS_NI_LUMA_OFFSET              110
#define IDS_NI_LUMA_SCALE               111
#define IDD_MOUSE_PANEL                 112
#define IDS_NI_FNAME_BASE               112
#define IDS_NI_FNAME_DARK               113
#define IDS_NI_FNAME_DETAIL             114
#define IDD_NIF_EXPORT                  115
#define IDS_NI_FNAME_DECAL1             115
#define IDD_DIALOG1                     116
#define IDS_NI_FNAME_DECAL2             116
#define IDD_USER_INTERFACE              116
#define IDD_IK_PANEL                    117
#define IDS_NI_FNAME_BUMP               117
#define IDS_NI_FNAME_GLOSS              118
#define IDD_PHYSIQUE_ERROR              119
#define IDS_NI_FNAME_GLOW               119
#define IDS_NI_TEXPORT_BASE             120
#define IDS_NI_TEXPORT_DARK             121
#define IDD_VIEWER_LOADING_PANEL        121
#define IDS_NI_TEXPORT_DETAIL           122
#define IDS_NI_TEXPORT_DECAL1           123
#define IDR_VIEWPORT_MENU               123
#define IDS_NI_TEXPORT_DECAL2           124
#define IDD_CAMERA_SELECTION_DIALOG     124
#define IDS_NI_TEXPORT_BUMP             125
#define IDS_NI_TEXPORT_GLOSS            126
#define IDS_NI_TEXPORT_GLOW             127
#define IDB_BITMAP1                     127
#define IDS_VIEWPORT_CLASSNAME          128
#define IDS_VIEWPORT_CATEGORY           129
#define IDS_NI_OPTIMIZATION_LABEL       130
#define IDS_NI_ABOUT_LABEL              132
#define IDD_PLATFORM_MATERIAL           132
#define IDS_NI_VIEWER_TYPE_LABEL        133
#define IDS_NI_SHADER_NAME              134
#define IDS_NI_EXPORT_TECHNIQUE_NAME    135
#define IDD_PROMPTFORERRORSDLG          135
#define IDS_NI_VIEWER_TECHNIQUE_NAME    136
#define IDS_NI_USENORMALMAPS            137
#define IDS_NI_NORMALMAP_TECHNIQUE_NAME 138
#define IDS_NI_REFLECTION_I             139
#define IDS_NI_REFLECTION               140
#define IDD_NETIMMERSE_SHADER           148
#define IDD_NETIMMERSE_SHADER_PSX2      150
#define IDD_NIF_EXPORT1                 151
#define IDD_TEXTURE_EXPORT              152
#define IDD_TEXTURE_EXPORT_PSX2         153
#define IDD_OPTIMIZATION_PANEL          154
#define IDD_ABOUT_PANEL                 156
#define IDD_BITMAP_TEXMAP               157
#define IDD_BITMAP_TIME                 158
#define ID_NETIMMERSE                   1000
#define ID_SPAWN                        1000
#define ID_LIVE                         1001
#define IDC_SCENEIMMERSE_VIEWER         1010
#define IDC_PHYSX_VIEWER                1011
#define IDC_SCENEIMMERSE_VIEWER2        1012
#define IDC_DX9_VIEWER                  1013
#define IDC_ANIMATION_VIEWER            1014
#define IDC_DX9_VIEWER2                 1015
#define IDC_D3D10_VIEWER                1015
#define IDC_ANIMATION_VIEWER2           1016
#define IDC_PHYSX_VIEWER2               1017
#define IDC_SELECTED                    1019
#define IDC_APP_TIME                    1019
#define IDC_CAM                         1020
#define IDC_LIGHTS                      1021
#define IDC_WINDOWED                    1022
#define IDC_TEXTURES                    1022
#define IDC_USE_ORIG                    1023
#define IDC_SP_WINDOW_Y                 1024
#define IDC_WEIGHTS                     1024
#define IDC_SP_WINDOW_Y_SPIN            1025
#define IDC_SEPARATE_SEQ                1025
#define IDC_UNUSEDUVS                   1025
#define IDC_BITMAP_TEXMAP_RATE          1025
#define ID_VIEW                         1026
#define ID_REGISTER                     1026
#define ID_HEADFIRST                    1026
#define ID_QUICKSAVE                    1026
#define ID_VIEW2                        1027
#define IDC_BITMAP_TEXMAP_RATE_SPIN     1028
#define IDC_SP_WINDOW_Y2                1028
#define IDC_FORWARD                     1029
#define IDC_FORWARD_MOD                 1029
#define IDC_SP_WINDOW_Y_SPIN2           1029
#define IDC_FORWARD_KEY                 1030
#define IDC_QUIT_KEY                    1031
#define IDC_DEFAULT_MOUSE               1032
#define IDC_TURN_RIGHT_KEY              1032
#define IDC_QUAKE_MOUSE                 1033
#define IDC_BACKWARD_KEY                1033
#define IDC_BMTEX_NAME                  1033
#define IDC_BACKWARD                    1034
#define IDC_CUSTOM_MOUSE                1034
#define IDC_BACKWARD_MOD                1034
#define IDC_TURN_RIGHT                  1035
#define IDC_FB_MOD_MS                   1035
#define IDC_FB_PRESS_MS                 1035
#define IDC_TURN_RIGHT_MOD              1035
#define IDC_TURN_LEFT                   1036
#define IDC_TURN_LR_MOD_MS              1036
#define IDC_TURN_LEFT_MOD               1036
#define IDC_SLIDE_RIGHT                 1037
#define IDC_SLIDE_LR_MOD_MS             1037
#define IDC_SLIDE_RIGHT_MOD             1037
#define IDC_SLIDE_LEFT                  1038
#define IDC_SLIDE_UD_MOD_MS             1038
#define IDC_SLIDE_LEFT_MOD              1038
#define IDC_SLIDE_UP                    1039
#define IDC_LOOK_UD_MOD_MS              1039
#define IDC_SLIDE_UP_MOD                1039
#define IDC_LOOK_DOWN                   1040
#define IDC_ROLL_LR_MOD_MS              1040
#define IDC_LOOK_DOWN_MOD               1040
#define IDC_AP_MOVEDIRX                 1041
#define IDC_LOOK_UP                     1041
#define IDC_FASTER_MOD_MS               1041
#define IDC_FB_MOD_MS2                  1041
#define IDC_LOOK_UP_MOD                 1041
#define IDC_AP_MOVEDIRXSPIN             1042
#define IDC_ROLL_LEFT                   1042
#define IDC_FB_MOD                      1042
#define IDC_FB_KEY_MS                   1042
#define IDC_ROLL_LEFT_MOD               1042
#define IDC_AP_MOVEDIRY                 1043
#define IDC_SLIDE_DOWN                  1043
#define IDC_FB_KEY                      1043
#define IDC_TURN_LR_KEY_MS              1043
#define IDC_SLIDE_DOWN_MOD              1043
#define IDC_AP_MOVEDIRYSPIN             1044
#define IDC_ROLL_RIGHT                  1044
#define IDC_SLIDE_LR_KEY_MS             1044
#define IDC_ROLL_RIGHT_MOD              1044
#define IDC_AP_MOVEDIRZ                 1045
#define IDC_SWITCH                      1045
#define IDC_SLIDE_UD_KEY_MS             1045
#define IDC_AP_MOVEDIRZSPIN             1046
#define IDC_RESET                       1046
#define IDC_LOOK_UD_KEY_MS              1046
#define IDC_AP_MOVEDIRZ2                1047
#define IDC_WIREFRAME                   1047
#define IDC_ROLL_LR_KEY_MS              1047
#define IDC_AP_MOVEDIRZSPIN2            1048
#define IDC_FASTER                      1048
#define IDC_TURN_LR_PRESS_MS            1048
#define IDC_SLIDE_RIGHT_KEY             1048
#define IDC_QUIT                        1049
#define IDC_SLIDE_LR_PRESS_MS           1049
#define IDC_TURN_LR_MOD                 1050
#define IDC_SP_KYBD_TR_SPIN             1050
#define IDC_SP_MS_TR                    1050
#define IDC_TURN_LR_KEY                 1051
#define IDC_SP_MS_TR_SPIN               1051
#define IDC_TURN_LEFT_KEY               1051
#define IDC_TOOL_PRIORITY_SPIN          1051
#define IDC_SLIDE_LR_MOD                1052
#define IDC_SP_MS_ROT                   1052
#define IDC_SLIDE_LEFT_KEY              1052
#define IDC_SLIDE_LR_KEY                1053
#define IDC_SP_MS_ROT_SPIN              1053
#define IDC_SLIDE_UP_KEY                1053
#define IDC_SLIDE_UD_MOD                1054
#define IDC_SP_KYBD_TR                  1054
#define IDC_SLIDE_UD_PRESS_MS           1054
#define IDC_SLIDE_UD_KEY                1055
#define IDC_SP_KYBD_ROT                 1055
#define IDC_LOOK_UD_PRESS_MS            1055
#define IDC_LOOK_UD_MOD                 1056
#define IDC_SP_KYBD_ROT_SPIN            1056
#define IDC_ROLL_LR_PRESS_MS            1056
#define IDC_LOOK_UD_KEY                 1057
#define IDC_TUMBLE_MODE                 1057
#define IDC_SLIDE_DOWN_KEY              1057
#define IDC_TOOL_PRIORITY               1057
#define IDC_ROLL_LR_MOD                 1058
#define IDC_REPORT_FRAME_RATE           1058
#define IDC_LOOK_UP_KEY                 1058
#define IDC_CCDSOLVER                   1058
#define IDC_ROLL_LR_KEY                 1059
#define IDC_LOOK_DOWN_KEY               1059
#define IDC_JTSOLVER                    1059
#define IDC_FASTER_MOD                  1060
#define IDC_ROLL_LEFT_KEY               1060
#define IDC_CS_AS_KEYFRAME              1060
#define IDC_ROLL_RIGHT_KEY              1061
#define IDC_INITSOLVE                   1061
#define IDC_EXPORT_CSASKEYFRAME         1061
#define IDC_RESET_KEY                   1062
#define IDC_PREVSOLVE                   1062
#define IDC_SWITCH_KEY                  1063
#define IDC_EXTRACT_KEYFRAMES           1063
#define IDC_WIREFRAME_KEY               1064
#define IDC_SRC_MODE                    1066
#define IDC_FIELD_MODE                  1066
#define IDC_ALPHA_SRC_MODE              1067
#define IDC_LIGHT_MODE                  1068
#define IDC_TOOL_PORT                   1068
#define IDC_ALPHA_DEST_MODE             1069
#define IDC_TOOL_TIMEOUT                1069
#define IDC_TOOL_TIMEOUT_SPIN           1070
#define IDC_APPLY_MODE                  1071
#define IDC_TOOL_PORT_SPIN              1071
#define IDC_TEST_MODE2                  1072
#define IDC_VIEWONPSX2                  1073
#define IDC_PS2_VIEWER                  1073
#define IDC_TOOL_IPADDRESS              1077
#define IDC_TARGETNAME                  1078
#define IDC_ALPHA_AUTOMATIC             1084
#define IDC_ALPHA_NONE                  1085
#define IDC_ALPHA_STANDARD              1086
#define IDC_ALPHA_ADDITIVE              1087
#define IDC_ALPHA_MULT                  1088
#define IDC_ALPHA_ADVANCED              1089
#define IDC_KF_MAINNIF                  1091
#define IDC_KF_ONE                      1092
#define IDC_KF_SEPARATE                 1093
#define IDC_TEX_MAINNIF                 1094
#define IDC_DEFAULT_KYBD                1095
#define IDC_TEX_ORIG                    1095
#define IDC_ONPLANE                     1096
#define IDC_QUAKE_KYBD                  1096
#define IDC_TEX_SEPARATE                1096
#define IDC_COLLISION                   1097
#define IDC_CUSTOM_KYBD                 1097
#define IDC_IMAGE_FILE_DIR              1097
#define IDC_FRAMERATE                   1098
#define IDC_TEX_QUAL_PAL                1098
#define IDC_TEX_QUAL_16                 1099
#define IDC_TEX_QUAL_32                 1100
#define IDC_TEX_QUAL_COMP               1101
#define IDC_PLATFORM                    1102
#define IDC_PROGRESS1                   1102
#define IDC_VIEWER_LOAD_PROGRESS        1102
#define IDC_NOWARN                      1103
#define IDC_STRIPIFY                    1103
#define IDC_TEX_ORIG_VRAM               1103
#define IDC_BITMAP_TEXMAP_RELOAD        1108
#define IDC_BITMAP_TEXMAP_LOOP          1119
#define IDC_BITMAP_TEXMAP_PINGPONG      1120
#define IDC_BITMAP_TEXMAP_HOLD          1121
#define IDC_PHYSIQUE_WARNING            1122
#define IDC_BITMAP_TEXMAP_START         1122
#define IDC_BITMAP_TEXMAP_START_SPIN    1123
#define IDC_CHECK1                      1124
#define IDC_PER_TEXTURE_OVERRIDE        1124
#define IDC_STRIPIFYCHECK               1124
#define IDC_NORMAL_MAP_CHECK            1124
#define IDC_U_MIRROR_CHECK              1124
#define IDC_ASK_AGAIN                   1124
#define IDC_USE_OLD_PSYS_CHECK          1124
#define IDC_COMBO1                      1125
#define IDC_TEXTURE_EXPORT_BASE         1125
#define IDC_UIMAP_SELECTIONS            1125
#define IDC_SHADER_COMBO                1125
#define IDC_U_TILE_CHECK                1125
#define IDC_SELECTED_MESH_PROFILE       1125
#define IDC_STRIPIFYCHECK2              1125
#define IDC_EDIT1                       1126
#define IDC_FILE_BASE                   1126
#define IDC_CUSTOM_FILENAME_EDIT        1126
#define IDC_MAXIMMERSE_ABOUT_EDIT       1126
#define IDC_SELECTED_SCRIPT             1126
#define IDC_SELECTED_PROCESS_SCRIPT     1126
#define IDC_SHADER_NOTES                1126
#define IDC_NETWORK_PATH_EDIT           1126
#define IDC_V_MIRROR_CHECK              1126
#define IDC_EDIT2                       1127
#define IDC_FILE_DECAL2                 1127
#define IDC_SELECTED_EXPORT_SCRIPT      1127
#define IDC_VIEWER_TECHNIQUE_COMBO      1127
#define IDC_V_TILE_CHECK                1127
#define IDC_EDIT3                       1128
#define IDC_FILE_DECAL1                 1128
#define IDC_EXPORT_TECHNIQUE_COMBO      1128
#define IDC_SKIN_PERCENTAGE_EDIT        1128
#define IDC_EDIT4                       1129
#define IDC_FILE_DETAIL                 1129
#define IDC_EDIT5                       1130
#define IDC_FILE_GLOW                   1130
#define IDC_EDIT6                       1131
#define IDC_FILE_DARK                   1131
#define IDC_COMBO2                      1132
#define IDC_TEXTURE_EXPORT_DARK         1132
#define IDC_NORMAL_MAP_COMBO            1132
#define IDC_COMBO3                      1133
#define IDC_TEXTURE_EXPORT_DETAIL       1133
#define IDC_COMBO4                      1134
#define IDC_TEXTURE_EXPORT_DECAL1       1134
#define IDC_COMBO5                      1135
#define IDC_TEXTURE_EXPORT_DECAL2       1135
#define IDC_COMBO6                      1136
#define IDC_TEXTURE_EXPORT_GLOW         1136
#define IDC_FILE_GLOSS                  1137
#define IDC_TEXTURE_EXPORT_GLOSS        1138
#define IDC_L_EDIT_BASE                 1141
#define IDC_L_SPIN_BASE                 1142
#define IDC_L_SPIN_DECAL2               1143
#define IDC_L_ON_BASE                   1144
#define IDC_L_ON_DETAIL                 1145
#define IDC_L_ON_DECAL2                 1146
#define IDC_K_EDIT_BASE                 1147
#define IDC_K_SPIN_BASE                 1148
#define IDC_K_SPIN_DECAL2               1149
#define IDC_K_ON_BASE                   1150
#define IDC_K_ON_DETAIL                 1151
#define IDC_K_ON_DECAL2                 1152
#define IDC_TEXTURE_EXPORT_BUTTON       1153
#define IDC_OK_BUTTON                   1154
#define IDC_VIEWER_STATIC_STRING        1155
#define IDC_VIEWER_LOAD_MESSAGE         1156
#define IDC_VIEWER_LOAD_MESSAGE_SPECIFIC 1157
#define IDC_SHOOTER_UI                  1158
#define IDC_DEFAULT_UI                  1159
#define IDC_CUSTOM_UI                   1160
#define IDC_CUSTOM_FILENAME_EDIT_BUTTON 1161
#define IDC_VIEW_UI                     1162
#define IDC_VIEW_UI_BUTTON              1162
#define IDC_CREATE_NEW_UIMAP_BUTTON     1163
#define IDC_OPTIMIZE_BUTTON             1164
#define IDC_XENON_VIEWER                1164
#define IDC_CAMERA_LIST                 1165
#define ID_OPTIMIZATION                 1166
#define IDC_CHOOSETARGET                1167
#define IDC_NTSC                        1168
#define IDC_VIEW_IMAGE                  1168
#define IDC_PAL                         1169
#define IDC_Z24                         1170
#define IDC_Z16                         1171
#define IDC_BITMAP                      1174
#define IDC_SELECT_SCRIPT_BUTTON        1175
#define IDC_EDIT_PROCESS_SCRIPT_BUTTON  1175
#define IDC_CUSTOM_VIEWER               1176
#define IDC_EDIT_EXPORT_SCRIPT_BUTTON   1176
#define IDC_SCENEIMMERSEOPTIONS         1177
#define IDC_SCENEIMMERSE_VIEWER_OPTIONS 1177
#define IDC_RELOAD_PROFILES             1177
#define IDC_RELOAD_PROFILES_BUTTON      1177
#define IDC_PHYSX_VIEWER_OPTIONS        1178
#define IDC_D3DOPTIONS                  1179
#define IDC_CUSTOM_VIEWER2              1179
#define IDC_SCENEIMMERSE_VIEWER_OPTIONS2 1180
#define IDC_XENON_VIEWER_OPTIONS        1181
#define IDC_CUSTOM_OPTIONS              1182
#define IDC_CUSTOM_VIEWER_OPTIONS       1182
#define IDC_CUSTOM_RENDERER_BUTTON      1183
#define IDC_EDIT_PROCESS_SCRIPT         1184
#define IDC_DX9_VIEWER_OPTIONS          1184
#define IDC_USE_TEMPLATE_SCRIPTS_CHECK  1185
#define IDC_EDIT_EXPORT_SCRIPT          1185
#define IDC_PS3_VIEWER_OPTIONS          1185
#define IDC_APPLY_SHADER_BUTTON         1186
#define IDC_WII_VIEWER_OPTIONS          1186
#define IDC_UPDATE_SHADER_BUTTON        1187
#define IDC_DX9_VIEWER_OPTIONS2         1187
#define IDC_D3D10_VIEWER_OPTIONS        1187
#define IDC_CUSTOM_VIEWER_OPTIONS2      1188
#define IDC_ANIMATION_VIEWER_OPTIONS    1189
#define IDC_ANIMATION_VIEWER_OPTIONS2   1190
#define IDC_CUSTOM_RENDERER_BUTTON2     1191
#define IDC_PHYSX_VIEWER_OPTIONS2       1192
#define IDC_WII_VIEWER_OPTIONS2         1193
#define IDC_NETWORK_SCRIPT_BUTTON       1194
#define IDC_SHADER_MOREINFO_BUTTON      1196
#define IDC_SHARE_ALL_BUTTON            1198
#define IDC_BMTEX_MAPCHANNEL_SPIN       1199
#define IDC_BMTEX_MAPCHANNEL            1200
#define IDC_IMAGE_QUALITY_RADIO1        1201
#define IDC_IMAGE_QUALITY_RADIO2        1202
#define IDC_IMAGE_QUALITY_RADIO3        1203
#define IDC_IMAGE_QUALITY_RADIO4        1204
#define IDC_IMAGE_QUALITY_RADIO5        1205
#define IDC_IMAGE_QUALITY_RADIO6        1206
#define IDC_IMAGE_QUALITY_RADIO7        1207
#define IDC_IMAGE_QUALITY_RADIO8        1208
#define IDC_IMAGE_QUALITY_RADIO9        1209
#define IDC_IMAGE_SIZE_RADIO1           1210
#define IDC_IMAGE_SIZE_RADIO2           1211
#define IDC_IMAGE_SIZE_RADIO3           1212
#define IDC_FILTER_RADIO1               1213
#define IDC_FILTER_RADIO2               1214
#define IDC_MIPMAP_RADIO1               1215
#define IDC_MIPMAP_RADIO2               1216
#define IDC_422_BEHAVIOR_CHECK          1216
#define IDC_MIPMAP_RADIO3               1217
#define IDC_AREA_SUPERSPRAY_CHECK       1217
#define IDC_U_OFFSET                    1218
#define IDC_OLD_SPINTIME_CHECK          1218
#define IDC_ALLOW_NPOT                  1218
#define IDC_ALLOW_NPOT_TEXTURES         1218
#define IDC_BMTEX_U_OFFSET_SPIN         1219
#define IDC_ALWAYS_SHOW_ERRORS_RADIO    1219
#define IDC_V_OFFSET                    1220
#define IDC_NEVER_SHOW_ERRORS_RADIO     1220
#define IDC_BMTEX_V_OFFSET_SPIN         1221
#define IDC_PROMPT_ERRORS_RADIO         1221
#define IDC_U_TILING                    1222
#define IDC_RADIO4                      1222
#define IDC_WRITE_ERRORS_TO_LOG_RADIO   1222
#define IDC_BMTEX_U_TILING_SPIN         1223
#define IDC_PS3_VIEWER                  1223
#define IDC_USE_OLD_NORMALS_CHECK       1223
#define IDC_OLD_NORMALS_CHECK           1223
#define IDC_V_TILING                    1224
#define IDC_STATIC8                     1224
#define IDC_WII_VIEWER                  1224
#define IDC_BMTEX_V_TILING_SPIN         1225
#define IDC_SPECULAR_ON                 1725
#define IDC_VERTEXCOLORS_ON             1726
#define IDC_ALPHATESTING_ON             1727
#define IDC_NOSORTER                    1728
#define IDC_L_ON                        1730
#define IDC_K_ON                        1731
#define IDC_L_ON7                       1731
#define IDC_L_ON_DARK                   1731
#define IDC_L_ON2                       1732
#define IDC_K_ON2                       1733
#define IDC_L_ON8                       1733
#define IDC_L_ON_DECAL1                 1733
#define IDC_L_ON3                       1734
#define IDC_K_ON3                       1735
#define IDC_L_ON9                       1735
#define IDC_L_ON_GLOW                   1735
#define IDC_L_ON4                       1736
#define IDC_L_ON_GLOSS                  1736
#define IDC_K_ON4                       1737
#define IDC_L_ON10                      1737
#define IDC_K_ON_DARK                   1737
#define IDC_L_ON5                       1738
#define IDC_K_ON5                       1739
#define IDC_L_ON11                      1739
#define IDC_K_ON_DECAL1                 1739
#define IDC_L_ON6                       1740
#define IDC_K_ON6                       1741
#define IDC_L_ON12                      1741
#define IDC_K_ON_GLOW                   1741
#define IDC_PS2_DARK_RGB                1742
#define IDC_PS2_DETAIL_RGB              1743
#define IDC_K_ON_GLOSS                  1744
#define IDC_SHININESS_EDIT              1807
#define IDC_SHININESS_SPIN              1808
#define IDC_ALPHA_EDIT                  1809
#define IDC_ALPHA_SPIN                  1810
#define IDC_TESTREF_EDIT                1811
#define IDC_TESTREF_SPIN                1812
#define IDC_AMB_COLOR                   1813
#define IDC_L_EDIT                      1814
#define IDC_PARALLAX_OFFSET_EDIT        1814
#define IDC_DIFF_COLOR                  1815
#define IDC_L_EDIT7                     1815
#define IDC_L_EDIT_DARK                 1815
#define IDC_SPEC_COLOR                  1816
#define IDC_L_EDIT8                     1816
#define IDC_L_EDIT_DETAIL               1816
#define IDC_MAPON_DIFF                  1817
#define IDC_L_EDIT9                     1817
#define IDC_L_EDIT_DECAL1               1817
#define IDC_EMITTANCE                   1818
#define IDC_L_EDIT10                    1818
#define IDC_L_EDIT_DECAL2               1818
#define IDC_L_SPIN                      1819
#define IDC_PARALLAX_OFFSET_SPIN        1819
#define IDC_K_EDIT                      1820
#define IDC_L_SPIN7                     1820
#define IDC_L_SPIN_DARK                 1820
#define IDC_K_SPIN                      1821
#define IDC_L_SPIN8                     1821
#define IDC_L_SPIN_DETAIL               1821
#define IDC_L_EDIT2                     1822
#define IDC_L_SPIN9                     1822
#define IDC_L_SPIN_DECAL1               1822
#define IDC_L_SPIN2                     1823
#define IDC_K_EDIT2                     1824
#define IDC_L_EDIT11                    1824
#define IDC_L_EDIT_GLOW                 1824
#define IDC_K_SPIN2                     1825
#define IDC_L_SPIN10                    1825
#define IDC_L_SPIN_GLOW                 1825
#define IDC_L_EDIT3                     1826
#define IDC_L_EDIT_GLOSS                1826
#define IDC_L_SPIN3                     1827
#define IDC_L_SPIN_GLOSS                1827
#define IDC_K_EDIT3                     1828
#define IDC_L_EDIT12                    1828
#define IDC_K_EDIT_DARK                 1828
#define IDC_K_SPIN3                     1829
#define IDC_L_SPIN11                    1829
#define IDC_K_SPIN_DARK                 1829
#define IDC_L_EDIT4                     1830
#define IDC_L_EDIT13                    1830
#define IDC_K_EDIT_DETAIL               1830
#define IDC_L_SPIN4                     1831
#define IDC_L_SPIN12                    1831
#define IDC_K_SPIN_DETAIL               1831
#define IDC_K_EDIT4                     1832
#define IDC_L_EDIT14                    1832
#define IDC_K_EDIT_DECAL1               1832
#define IDC_K_SPIN4                     1833
#define IDC_L_SPIN13                    1833
#define IDC_K_SPIN_DECAL1               1833
#define IDC_L_EDIT5                     1834
#define IDC_L_EDIT15                    1834
#define IDC_K_EDIT_DECAL2               1834
#define IDC_L_SPIN5                     1835
#define IDC_K_EDIT5                     1836
#define IDC_L_EDIT16                    1836
#define IDC_K_EDIT_GLOW                 1836
#define IDC_K_SPIN5                     1837
#define IDC_L_SPIN14                    1837
#define IDC_K_SPIN_GLOW                 1837
#define IDC_L_EDIT6                     1838
#define IDC_K_EDIT_GLOSS                1838
#define IDC_L_SPIN6                     1839
#define IDC_K_SPIN_GLOSS                1839
#define IDC_K_EDIT6                     1840
#define IDC_K_SPIN6                     1841
#define IDC_LUMA_OFFSET_EDIT            1842
#define IDC_LUMA_OFFSET_SPIN            1843
#define IDC_LUMA_SCALE_EDIT             1844
#define IDC_LUMA_SCALE_SPIN             1845
#define IDC_BUMP_MAGNITUDE_EDIT         1846
#define IDC_BUMP_MAGNITUDE_SPIN         1847
#define IDC_PLATFORM_MATERIAL_VP_USE1   1895
#define IDC_PLATFORM_MATERIAL_VP_USE2   1896
#define IDC_PLATFORM_MATERIAL_VP_USE3   1897
#define IDC_PLATFORM_MATERIAL_VP_USE4   1898  
#define IDC_PLATFORM_MATERIAL_VP_USE5   1899
#define IDC_MTL_ONE                     1900
#define IDC_MTL_TWO                     1901
#define IDC_MTL_THREE                   1902
#define IDC_MTL_TWO2                    1903
#define IDC_MTL_FOUR                    1904
#define IDC_MTL_FIVE                    1905
#define IDC_SP_WINDOW_X                 3044
#define IDC_SP_WINDOW_X_SPIN            3045
#define IDC_SP_WINDOW_X2                3046
#define IDC_SP_WINDOW_X_SPIN2           3047
#define IDS_NI_PLATFORM_MATERIAL        11714
#define IDS_NI_MTL_ONE                  11715
#define IDS_NI_MTL_TWO                  11716
#define IDS_NI_PLATFORM_MTL_PARAMS      11717
#define IDS_NI_VP_MTL                   11718
#define IDS_NI_MTL_THREE                11720
#define IDS_NI_MTL_FOUR                 11721
#define IDS_NI_PLATFORM_MTL_BASE_PARAMETERS 11722
#define IDS_DS_BITMAP_TEXTURE_ERR       11723
#define IDS_DS_BITMAP                   11724
#define IDS_DS_BITMAP_CDESC             11725
#define IDS_DS_BITMAP_PARAMS            11726
#define IDC_BITMAP_TEXMAP_NAME          11727
#define IDS_DS_COORDINATES              11728
#define IDS_JW_FILENAME                 11729
#define IDS_DS_TIME_PARAMS              11730
#define IDS_PW_STARTTIME                11731
#define IDS_PW_PLAYBACK                 11732
#define IDS_PW_ENDCONDITION             11733
#define IDS_DS_SELECT_BMFILE            11734
#define IDS_DS_IMAGE_DISPLAY_TITLE      11735
#define IDS_DS_PARAMCHG                 11736
#define IDS_DS_OUTPUT                   11737
#define IDS_DS_PARAMETERS               11738
#define IDS_NI_L7                       11740
#define IDS_NI_LON7                     11741
#define IDS_NI_K7                       11742
#define IDS_NI_KON7                     11743 
#define IDS_NI_MTL_FIVE                 11744
#define IDM_UPDATE_VIEWPORT             40001
#define IDM_USE_CS_KEYFRAMES            40002
#define IDM_EDIT_UIMAP                  40003
#define IDM_OPTIONS_EDIT_UIMAP          40003
#define IDM_SCENEGRAPHVIEW              40004
#define IDM_OPTIONS_SCENEGRAPHVIEW      40004
#define IDM_USE_MAX_MOUSE_EMULATION     40005
#define IDM_USE_MAX_ANIM                40009
#define IDM_WIREFRAME                   40010
#define IDM_OVERDRAW                    40011
#define IDM_VIEW_MAXVIEW                40018
#define IDM_OPTIONS_BACKGROUNDCOLOR     40019
#define IDM_RESET_CAMERA                40021
#define IDM_STRIPIFYCHECK               40024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
